### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by MistzSoftware** [algosup/2023-2024-project-5-flutter-team-6#44]
The title of each category is truncate vertically
![](https://media.discordapp.net/attachments/631179722503487488/1249746475215360051/Screenshot_20240610_172544_com.example.adopte_un_candidat.jpg?ex=66686c9a&is=66671b1a&hm=33132d73a46f031e02dbc8f456d5dcc0fc2c831796b8db8a80a705d862996c57&=&format=webp&width=274&height=593)
![](https://media.discordapp.net/attachments/631179722503487488/1249746475475271720/Screenshot_20240610_172546_com.example.adopte_un_candidat.jpg?ex=66686c9a&is=66671b1a&hm=f478ee79bbf06943776ca715cdeebbda47e4fc20aa9c49d4212fa589feee65b0&=&format=webp&width=274&height=593)
![](https://media.discordapp.net/attachments/631179722503487488/1249746475739644047/Screenshot_20240610_172550_com.example.adopte_un_candidat.jpg?ex=66686c9a&is=66671b1a&hm=480c07e4576afecb064e8859a0077511949a23ac76645be81ad1263fc5909f3f&=&format=webp&width=274&height=593)
![](https://media.discordapp.net/attachments/631179722503487488/1249746476020666409/Screenshot_20240610_172548_com.example.adopte_un_candidat.jpg?ex=66686c9b&is=66671b1b&hm=608c39384eaa34e3a632b58e0e4598a16083891b03c294632c6bce0c91bf8520&=&format=webp&width=274&height=593)

**Comment by MistzSoftware** [comment]
@Evan-UHRING what's new about the issue?

**Comment by MistzSoftware** [comment]
New field with the same issue

![](https://media.discordapp.net/attachments/631179722503487488/1250913403036241930/Screenshot_20240613_224230_com.example.adopte_un_candidat.jpg?ex=666cab64&is=666b59e4&hm=c256f299ae3cc06b18ad5158c19bea1a990c9da76ce5fbc2cbdba473f10ad29c&=&format=webp&width=274&height=593)

**Comment by Ianlaur** [comment]
Fixed (commit: 55dcdea)
