### ISSUE TITLE
Missing back button

### ISSUE THREAD

**Issue by MistzSoftware** [algosup/2023-2024-project-5-flutter-team-6#64]
The back arrow is missing on this page.

![](https://media.discordapp.net/attachments/631179722503487488/1250913403288158371/Screenshot_20240613_224210_com.example.adopte_un_candidat.jpg?ex=666cab64&is=666b59e4&hm=ab63347f3e572611e6fdc162dd52d1a808dfb9b6a350612bd97f0b1c911f6037&=&format=webp&width=274&height=593)

**Comment by Evan-UHRING** [comment]
the back button has been added
