### ISSUE TITLE
Non working buttons

### ISSUE THREAD

**Issue by MistzSoftware** [algosup/2023-2024-project-5-flutter-team-6#65]
the next button and the pass button don't work.

![](https://media.discordapp.net/attachments/631179722503487488/1250913403288158371/Screenshot_20240613_224210_com.example.adopte_un_candidat.jpg?ex=666cab64&is=666b59e4&hm=ab63347f3e572611e6fdc162dd52d1a808dfb9b6a350612bd97f0b1c911f6037&=&format=webp&width=274&height=593)

![](https://media.discordapp.net/attachments/631179722503487488/1250913403036241930/Screenshot_20240613_224230_com.example.adopte_un_candidat.jpg?ex=666cab64&is=666b59e4&hm=c256f299ae3cc06b18ad5158c19bea1a990c9da76ce5fbc2cbdba473f10ad29c&=&format=webp&width=274&height=593)

**Comment by Evan-UHRING** [comment]
the buttons are now working
